### PR TITLE
Preprocess: improve formatting

### PR DESCRIPTION
**Pull request by PeterFeicht**
As discussed recently here are a few formatting improvements.

### CODE REVIEW

**Comment by PeterFeicht** [comment]
Missed that, I need to get in the habit of running `test.sh` before committing...

The missing blank line is easy to fix, but I don't really know what to do with the other issue. flake8 seems to accept a continuation indent of 2 in other cases, but not in this case. Should I suppress the error or just give in and use one level of indentation?

**Comment by p12tic** [comment]
I think that the other cases are arguments in function call and this one is statement splitting via '\'. I think just give it single indent. Thanks!

**Comment by PeterFeicht** [comment]
Done. I also fixed two pylint warnings that I didn't get locally (with the same command line the CI uses), which is strange.

Please have a look at 30c065a, I'm pretty sure the indentation was a mistake since the code was dead this way.

**Comment by p12tic** [comment]
Thanks for fixing the extra issue. Indeed, the previous code look wrong to me too.

**Pull request merged**
