### PR TITLE
Link fixes

### PR DESCRIPTION
**Pull request by PeterFeicht**
This fixes two small issues:
 * A wrong link in the site CSS caused a missing icon for external links to PDF files.
 * Images have an info icon that links to the online info page for the image file.

### CODE REVIEW

**Comment by p12tic** [comment]
Can we have a test? Otherwise, LGTM.

**Comment by PeterFeicht** [comment]
Should have thought of that, I'll add one for `remove_fileinfo`. I'll also split out the other thing I forgot last time.

**Comment by PeterFeicht** [comment]
I split out removal of unused external links and added tests for both that and `remove_fileinfo`. In the process I also added adjustment of the favicon path. I noticed that you don't actually remove the favicon so this might have been an oversight, if you don't want a favicon I can remove it too.

**Comment by p12tic** [comment]
Thanks!

**Pull request merged**
