### PR TITLE
Enable pylint and flake8 warnings

### PR DESCRIPTION
**Pull request by p12tic**

### CODE REVIEW

**Comment by PeterFeicht** [comment]
Aw man, I really wish you hadn't chosen such a small line length limit. 80 characters just seems unnecessary these days :-/
Any chance you might consider upping that?

**Comment by p12tic** [comment]
It turned out that 80 characters is almost the maximum that can be displayed side by side without compromising readability on my editor of choice on a full HD monitor. So for this reason I'd like to stick to 80 characters. Myself I do find it limiting sometimes, but not enough to consider to switch. Sorry for declining your suggestion.

**Comment by PeterFeicht** [comment]
Alright, I'll learn to live with it I guess :-)
Did you do the formatting manually, or was that done by a tool?

**Comment by p12tic** [comment]
There's autopep8, but I found it wraps lines at "wrong" places, so this time I did it manually.

**Comment by PeterFeicht** [comment]
I'm asking because I thought a few things were wrapped very weirdly. Would you be open to a couple small changes in that regard?

**Comment by p12tic** [comment]
Could you give some links?

**Comment by PeterFeicht** [comment]
[preprocess.py:131](https://github.com/p12tic/cppreference-doc/blob/066625810b8fea5788878192d0b60a17dc89d3b6/commands/preprocess.py#L131) or [preprocess.py:224](https://github.com/p12tic/cppreference-doc/blob/066625810b8fea5788878192d0b60a17dc89d3b6/commands/preprocess.py#L224) for example, I think they'd look better when wrapped earlier. Or in [preprocess_qch.py](https://github.com/p12tic/cppreference-doc/blob/066625810b8fea5788878192d0b60a17dc89d3b6/preprocess_qch.py#L64) I'd move the `enumerate` into the next loop, since the index is not needed before that.

**Comment by p12tic** [comment]
Agreed.

**Comment by PeterFeicht** [comment]
Great, then I'll do a PR sometime.

**Pull request merged**
