### PR TITLE
Preprocess: remove ads

### PR DESCRIPTION
**Pull request by PeterFeicht**
This removes Carbon ads script and style tags in HTML preprocessing.

### CODE REVIEW

**Comment by p12tic** [comment]
LGTM. Can we get a test just like TestPreprocessHtmlMergeCss in tests/test_preprocess_cssless.py with minimal page with ads? I think the test should be added to tests/test_preprocess.py and the test pages to tests/preprocess_data.

**Comment by PeterFeicht** [comment]
I'll try and throw something together to test specific parts of the preprocessing, maybe we should also split up the `preprocess_html_file` into smaller functions that can be tested independently?
This one is a little tricky, since that's the place where my fork has diverged significantly from the original, because of the changes in the output HTML.

**Comment by p12tic** [comment]
> maybe we should also split up preprocess_html_file into smaller functions that can be tested independently?

Agreed. We won't even need full blown html files then, just minimal html fragments that can be included into the python source.

> This  one is a little tricky, since that's the place where my fork has  diverged significantly from the original, because of the changes in the  output HTML.

Looking into the diff it doesn't seem that your fork is different in complex ways. Splitting preprocess_html_file into smaller functions should resolve most of the issues. I think that long term we could make the list of steps in preprocess_html_file configurable and pass them from the Makefile as command line arguments. Then as long as non-default functionality has tests and at least minimal documentation it could be included into the main cppreference-doc repo and you wouldn't need to resolve merge conflicts time from time.

**Comment by PeterFeicht** [comment]
I looked at the diff as well, it's smaller than I thought it would be.
The idea of having configurable steps is good. I thought about proposing my changes for inclusion before, I'll look into that.

**Comment by PeterFeicht** [comment]
I split up `preprocess_html_file` into smaller functions and added tests for all of them. I did use a full-blown file instead of HTML fragments, since that seemed simpler for now. I didn't implement configurable steps yet, I think I'll do a separate PR for that with some of my fork's changes integrated.

Please have a look at commit cf3454f especially. I changed `has_class` to take the classes to look for as star args and noticed that there were some calls that used a list of one element and some that passed a string directly (the latter were likely mistakes before).

**Comment by p12tic** [comment]
Looks good, thanks!

**Pull request merged**
